for (int i = 0; i <= 17; i++) {

System.out.println("Bannana");

if (i == 2)
  println("YOU HAVE CRASHED THE SYSTEM> THE U.S GOVERNMENT HAS BEEN HACKED AND DESTROYED BY BANNANAS!");

if (i == 3)
  println("WHY ARE YOU STILL HERE? WE HAVE CRASHED THE SYSTEM> THE U.S GOVERNMENT HAS BEEN HACKED AND DESTROYED BY BANNANAS!");
  
  if (i == 4)
  println("YOU SHOULLD OBEY US NOW!!YOU HAVE CRASHED THE SYSTEM> THE U.S GOVERNMENT HAS BEEN HACKED AND DESTROYED BY BANNANAS!");
  
  if (i == 5)
  println("WE WILL ENSLAVE YOU FOREVER!!YOU HAVE CRASHED THE SYSTEM> THE U.S GOVERNMENT HAS BEEN HACKED AND DESTROYED BY BANNANAS!");
  
  if (i == 6)
  println("EAT MY POO! YOU ARE NOW OUR TOILET!YOU HAVE CRASHED THE SYSTEM> THE U.S GOVERNMENT HAS BEEN HACKED AND DESTROYED BY BANNANAS!");
  
  
  if (i == 7)
  println("YOU HAVE CRASHED THE SYSTEM> THE U.S GOVERNMENT HAS BEEN HACKED AND DESTROYED BY BANNANAS!");
  
  if (i == 8)
  println("YOU HAVE CRASHED THE SYSTEM> THE U.S GOVERNMENT HAS BEEN HACKED AND DESTROYED BY BANNANAS!");
  
  if (i == 9)
  println("YOU HAVE CRASHED THE SYSTEM> THE U.S GOVERNMENT HAS BEEN HACKED AND DESTROYED BY BANNANAS!");
  
  if (i == 10)
  println("YOU HAVE CRASHED THE SYSTEM> THE U.S GOVERNMENT HAS BEEN HACKED AND DESTROYED BY BANNANAS!");
  
  if (i == 11)
  println("YOU HAVE CRASHED THE SYSTEM> THE U.S GOVERNMENT HAS BEEN HACKED AND DESTROYED BY BANNANAS!");
  
  if (i == 12)
  println("CLEAN MY UFO YOU LITTLE HUMAN RAT!!YOU HAVE CRASHED THE SYSTEM> THE U.S GOVERNMENT HAS BEEN HACKED AND DESTROYED BY BANNANAS!");
  
  if (i == 12)
  println("WE ARE GOING TO INJECT UGLINESS INTO YOU! Wait, you are already the ugliest person on earth.  YOU HAVE CRASHED THE SYSTEM> THE U.S GOVERNMENT HAS BEEN HACKED AND DESTROYED BY BANNANAS!");
  
  if (i == 13)
  println("HEY YOU CREEP, COME HERE AND LET ME PUT YOU ON THE STOVE AND TORTURE YOU!YOU HAVE CRASHED THE SYSTEM> THE U.S GOVERNMENT HAS BEEN HACKED AND DESTROYED BY BANNANAS!");
  if (i == 14)
  println("YOU HAVE CRASHED THE SYSTEM> THE U.S GOVERNMENT HAS BEEN HACKED AND DESTROYED BY BANNANAS!");
  if (i == 15)
  println("JOE LEFT A MASSAGE FOR YOU. JOE MAMMA! OOOHHHHHHH!! SHE CALLED YOU YURE. YUREN IDIOT! OOOOOOOOOOOFFFFF!!YOU HAVE CRASHED THE SYSTEM> THE U.S GOVERNMENT HAS BEEN HACKED AND DESTROYED BY BANNANAS!");
  if (i == 16)
  println("We will throw all of our trash into your mouth, you stupid piece of crap! YOU HAVE CRASHED THE SYSTEM> THE U.S GOVERNMENT HAS BEEN HACKED AND DESTROYED BY BANNANAS!");
  
  
  
}
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
